plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  eslint:
    enabled: true

exclude_patterns:
  - "**/.*"
  - "**/*"
  - "!src/**/*.ts"
  - "**/*.spec.ts"
