name: Lint & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run lint
  test:
    name: Test ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
         - 10.x
         - 12.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

      - uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: ${{ github.workspace }}/test-reports/**/*
