name: Release

on:
  workflow_run:
    workflows:
      - "Code checks and tests"
    branches:
      - master
    types:
      - completed

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - name: Run build
        run: npm run build
      - uses: cycjimmy/semantic-release-action@master
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/npm
            @semantic-release/git
            @semantic-release/changelog
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
